// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SisCras.Database;

#nullable disable

namespace SisCras.Migrations
{
    [DbContext(typeof(SisCrasDbContext))]
    [Migration("20251022184009_DesativarUsuarioFamilia")]
    partial class DesativarUsuarioFamilia
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("SisCras.Models.Cras", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cras");
                });

            modelBuilder.Entity("SisCras.Models.Familia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConfiguracaoFamiliar")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Familias");
                });

            modelBuilder.Entity("SisCras.Models.FamiliaUsuario", b =>
                {
                    b.Property<int>("FamiliaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Parentesco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FamiliaId", "UsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("FamiliaUsuarios");
                });

            modelBuilder.Entity("SisCras.Models.Prontuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Codigo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CrasId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DataSaida")
                        .HasColumnType("TEXT");

                    b.Property<int>("FamiliaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FormaDeAcesso")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TecnicoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CrasId");

                    b.HasIndex("FamiliaId");

                    b.HasIndex("TecnicoId");

                    b.ToTable("Prontuarios");
                });

            modelBuilder.Entity("SisCras.Models.Tecnico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tecnicos");
                });

            modelBuilder.Entity("SisCras.Models.TecnicoCras", b =>
                {
                    b.Property<int>("CrasId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TecnicoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DataEntrada")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DataSaida")
                        .HasColumnType("TEXT");

                    b.HasKey("CrasId", "TecnicoId");

                    b.HasIndex("TecnicoId");

                    b.ToTable("TecnicoCras");
                });

            modelBuilder.Entity("SisCras.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<int>("Escolaridade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstadoCivil")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FonteRenda")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeSocial")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ocupacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrientacaoSexual")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Profissao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Raca")
                        .HasColumnType("INTEGER");

                    b.Property<float>("RendaBruta")
                        .HasColumnType("REAL");

                    b.Property<string>("Rg")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Sexo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SisCras.Models.FamiliaUsuario", b =>
                {
                    b.HasOne("SisCras.Models.Familia", "Familia")
                        .WithMany("FamiliaUsuarios")
                        .HasForeignKey("FamiliaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SisCras.Models.Usuario", "Usuario")
                        .WithMany("FamiliaUsuarios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Familia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SisCras.Models.Prontuario", b =>
                {
                    b.HasOne("SisCras.Models.Cras", "Cras")
                        .WithMany("Prontuarios")
                        .HasForeignKey("CrasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SisCras.Models.Familia", "Familia")
                        .WithMany("Prontuarios")
                        .HasForeignKey("FamiliaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SisCras.Models.Tecnico", "Tecnico")
                        .WithMany("Prontuarios")
                        .HasForeignKey("TecnicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cras");

                    b.Navigation("Familia");

                    b.Navigation("Tecnico");
                });

            modelBuilder.Entity("SisCras.Models.TecnicoCras", b =>
                {
                    b.HasOne("SisCras.Models.Cras", "Cras")
                        .WithMany("TecnicosCras")
                        .HasForeignKey("CrasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SisCras.Models.Tecnico", "Tecnico")
                        .WithMany("TecnicoCras")
                        .HasForeignKey("TecnicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cras");

                    b.Navigation("Tecnico");
                });

            modelBuilder.Entity("SisCras.Models.Cras", b =>
                {
                    b.Navigation("Prontuarios");

                    b.Navigation("TecnicosCras");
                });

            modelBuilder.Entity("SisCras.Models.Familia", b =>
                {
                    b.Navigation("FamiliaUsuarios");

                    b.Navigation("Prontuarios");
                });

            modelBuilder.Entity("SisCras.Models.Tecnico", b =>
                {
                    b.Navigation("Prontuarios");

                    b.Navigation("TecnicoCras");
                });

            modelBuilder.Entity("SisCras.Models.Usuario", b =>
                {
                    b.Navigation("FamiliaUsuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
