// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SisCras.Database;

#nullable disable

namespace SisCras.Migrations
{
    [DbContext(typeof(SisCrasDbContext))]
    [Migration("20251020112120_FamiliaAdded")]
    partial class FamiliaAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("SisCras.Models.Familia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Familias");
                });

            modelBuilder.Entity("SisCras.Models.Prontuario", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Codigo")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("FormaDeAcesso")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Prontuarios");
                });

            modelBuilder.Entity("SisCras.Models.Tecnico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tecnicos");
                });

            modelBuilder.Entity("SisCras.Models.Prontuario", b =>
                {
                    b.HasOne("SisCras.Models.Familia", "Familia")
                        .WithMany("Prontuarios")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SisCras.Models.Tecnico", "Tecnico")
                        .WithMany("Prontuarios")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Familia");

                    b.Navigation("Tecnico");
                });

            modelBuilder.Entity("SisCras.Models.Familia", b =>
                {
                    b.Navigation("Prontuarios");
                });

            modelBuilder.Entity("SisCras.Models.Tecnico", b =>
                {
                    b.Navigation("Prontuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
